adding persistent faiss db

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -66,7 +66,7 @@ jobs:
             sudo docker images || { echo "Failed to list Docker images"; exit 1; }
 
             echo "Running the Docker container..."
-            sudo docker run -d --name qcm-app --env-file ./rag-app/.env -p 80:8000 qcm-app || { echo "Docker run failed"; exit 1; }
+            sudo docker run -d --name qcm-app -v /home/ubuntu/qcm-generator-rag-app/faiss_db:/app/faiss_db --env-file ./rag-app/.env -p 80:8000 qcm-app || { echo "Docker run failed"; exit 1; }
 
             echo "Checking Docker container status..."
             sudo docker ps -a || { echo "Docker ps failed"; exit 1; }
